import { Dict } from '../Dict'

type ChartValidationSettingsJson = Dict<any>

export class ChartValidationSettings {
    VALIDATE_DUPLICATE_LABELS: string
    VALIDATE_EMPTY_FLOOR: string
    VALIDATE_FOCAL_POINT: string
    VALIDATE_OBJECTS_WITHOUT_CATEGORIES: string
    VALIDATE_OBJECT_TYPES_PER_CATEGORY: string
    VALIDATE_UNLABELED_OBJECTS: string

    constructor (json: ChartValidationSettingsJson) {
        this.VALIDATE_DUPLICATE_LABELS = json.VALIDATE_DUPLICATE_LABELS
        this.VALIDATE_OBJECTS_WITHOUT_CATEGORIES = json.VALIDATE_OBJECTS_WITHOUT_CATEGORIES
        this.VALIDATE_UNLABELED_OBJECTS = json.VALIDATE_UNLABELED_OBJECTS
        this.VALIDATE_FOCAL_POINT = json.VALIDATE_FOCAL_POINT
        this.VALIDATE_OBJECT_TYPES_PER_CATEGORY = json.VALIDATE_OBJECT_TYPES_PER_CATEGORY
        this.VALIDATE_EMPTY_FLOOR = json.VALIDATE_EMPTY_FLOOR
    }
}
